#!/usr/bin/env python3
import os
import shutil

# Generate files.html
files = os.listdir("web/files")
content = "<!--This file was automatically generated by a python script-->"
content += "<h1>Files</h1>\n"
for f in sorted(files):
  content += '<a href="web/files/' + f + '">\n'
  content += f + '</a><br />\n'

fo = open("web/sites/files.html", "w")
fo.write(content)
fo.close()
